plugins {
    id('com.android.library')
    id('dev.rikka.tools.refine') version '4.4.0'
}

android {
    namespace 'rikka.shizuku.server'
    compileSdk rootProject.ext.compile_sdk
    buildToolsVersion rootProject.ext.build_tools
    ndkVersion rootProject.ext.ndk_version

    defaultConfig {
        minSdk rootProject.ext.min_sdk
        targetSdk rootProject.ext.target_sdk
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.3.0'
    implementation 'androidx.core:core:1.16.0'
    implementation 'dev.rikka.rikkax.parcelablelist:parcelablelist:2.0.1'

    api project(':shizuku-aidl')
    api project(':shizuku-shared')
    api project(':shizuku-rish')

    implementation "dev.rikka.tools.refine:runtime:${refine_version}"
    implementation "dev.rikka.hidden:compat:4.3.3"
    compileOnly "dev.rikka.hidden:stub:4.3.3"
}
