/*
 * Copyright (c) 2018 Hai Zhang <dreaming.in.code.zh@gmail.com>
 * All Rights Reserved.
 */

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-parcelize'

android {
    namespace 'me.zhanghai.android.files'
    buildToolsVersion rootProject.ext.build_tools
    compileSdk rootProject.ext.compile_sdk
    ndkVersion rootProject.ext.ndk_version
    defaultConfig {
        minSdk rootProject.ext.min_sdk
        targetSdk rootProject.ext.target_sdk
        versionCode 39
        versionName '1.7.4'
        resValue 'string', 'app_version', versionName + ' (' + versionCode + ')'

        buildConfigField "String", "APPLICATION_ID", "\"me.zhanghai.android.files\""
        buildConfigField "int", "VERSION_CODE", "${versionCode}"
        buildConfigField "String", "VERSION_NAME", "\"${versionName}\""
        buildConfigField "String", "FILE_PROVIDER_AUTHORITY", "\"me.zhanghai.android.files.file_provider\""

        resValue 'string', 'app_provider_authority', 'me.zhanghai.android.files.app_provider'
        resValue 'string', 'file_provider_authority', 'me.zhanghai.android.files.file_provider'

        externalNativeBuild {
            cmake {
                version "4.1.1"
                arguments '-DANDROID_STL=none'
            }
        }
        consumerProguardFiles "consumer-rules.pro"
    }
    buildFeatures {
        aidl true
        buildConfig true
        viewBinding true
    }
    androidResources {
        // generateLocaleConfig true
    }
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8.toString()
    }
    externalNativeBuild {
        cmake {
            path 'CMakeLists.txt'
        }
    }
    lint {
        warning 'InvalidPackage', 'MissingTranslation'
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        jniLibs {
            useLegacyPackaging true
        }
        resources {
            excludes += [
                    'META-INF/DEPENDENCIES',
                    'org/bouncycastle/pqc/crypto/picnic/*'
            ]
        }
    }
}

repositories {
    maven {
        url 'https://jitpack.io'
    }
}
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.5")

    implementation('com.github.bitfireAT:dav4jvm:ec6264d427') {
        exclude group: 'org.ogce', module: 'xpp3'
    }
    implementation 'com.github.chrisbanes:PhotoView:2.3.0'
    implementation project(':libsu-service')

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    def kotlinx_coroutines_version = '1.10.2'
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$kotlinx_coroutines_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$kotlinx_coroutines_version"

    implementation 'androidx.activity:activity-ktx:1.10.1'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.core:core-ktx:1.16.0'
    implementation 'androidx.drawerlayout:drawerlayout:1.2.0'
    implementation 'androidx.exifinterface:exifinterface:1.4.1'
    implementation 'androidx.fragment:fragment-ktx:1.8.8'
    def androidx_lifecycle_version = '2.9.2'
    implementation "androidx.lifecycle:lifecycle-common-java8:$androidx_lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$androidx_lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-process:$androidx_lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$androidx_lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$androidx_lifecycle_version"
    implementation 'androidx.preference:preference-ktx:1.2.1'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'com.google.android.material:material:1.12.0'

    implementation 'com.caverock:androidsvg-aar:1.4'
    implementation 'com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0'
    implementation 'com.drakeet.drawer:drawer:1.0.3'
    implementation 'com.h6ah4i.android.materialshadowninepatch:materialshadowninepatch:1.0.0'
    implementation 'com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:1.0.0'
    implementation ('com.hierynomus:smbj:0.11.5') {
        exclude group: 'org.bouncycastle', module: 'bcprov-jdk15on'
    }
    def bouncy_castle_version = '1.81'
    implementation "org.bouncycastle:bcprov-jdk15to18:$bouncy_castle_version"
    implementation ('com.hierynomus:sshj:0.40.0') {
        exclude group: 'org.bouncycastle', module: 'bcprov-jdk18on'
        exclude group: 'org.bouncycastle', module: 'bcpkix-jdk18on'
    }
    implementation "org.bouncycastle:bcpkix-jdk15to18:$bouncy_castle_version"
    implementation 'com.leinardi.android:speed-dial:3.3.0'
    implementation ('com.rapid7.client:dcerpc:0.12.13') {
        exclude group: 'com.google.guava', module: 'guava'
        exclude group: 'com.hierynomus', module: 'smbj'
        exclude group: 'org.bouncycastle', module: 'bcprov-jdk18on'
    }
    implementation 'com.google.guava:guava:33.4.8-android'
    implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'
    implementation 'com.takisoft.preferencex:preferencex:1.1.0'
    implementation 'commons-net:commons-net:3.12.0'
    implementation 'de.psdev.licensesdialog:licensesdialog:2.1.0'
    implementation 'dev.chrisbanes:insetter-ktx:0.3.1'
    implementation 'dev.rikka.rikkax.preference:simplemenu-preference:1.0.3'
    implementation project(':shizuku-api')
    implementation ('eu.agno3.jcifs:jcifs-ng:2.1.10') {
        exclude group: 'org.bouncycastle', module: 'bcprov-jdk18on'
    }
    implementation platform('io.coil-kt:coil-bom:2.7.0')
    implementation 'io.coil-kt:coil'
    implementation 'io.coil-kt:coil-gif'
    implementation 'io.coil-kt:coil-svg'
    implementation 'io.coil-kt:coil-video'
    implementation 'me.zhanghai.android.appiconloader:appiconloader:1.5.0'
    implementation 'me.zhanghai.android.fastscroll:library:1.3.0'
    implementation 'me.zhanghai.android.foregroundcompat:library:1.0.2'
    implementation 'me.zhanghai.android.libarchive:library:1.1.6'
    implementation 'me.zhanghai.android.libselinux:library:2.1.1'
    implementation 'me.zhanghai.android.retrofile:library:1.2.0'
    implementation 'me.zhanghai.android.systemuihelper:library:1.0.0'
    implementation 'org.apache.ftpserver:ftpserver-core:1.2.1'
    implementation ('org.apache.mina:mina-core') {
        version {
            strictly '2.1.3'
        }
    }
    implementation 'org.slf4j:slf4j-android:1.7.36'
}
