plugins {
    id('com.android.library')
}

android {
    namespace 'rikka.rish'
    compileSdk rootProject.ext.compile_sdk
    buildToolsVersion rootProject.ext.build_tools
    ndkVersion rootProject.ext.ndk_version

    defaultConfig {
        minSdk rootProject.ext.min_sdk
        targetSdk rootProject.ext.target_sdk

        externalNativeBuild {
            cmake {
                arguments '-DANDROID_STL=none'
            }
        }
    }
    buildFeatures {
        prefab true
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    externalNativeBuild {
        cmake {
            path 'src/main/cpp/CMakeLists.txt'
            version "4.1.1"
        }
    }
}

dependencies {
    implementation project(':shizuku-api')

    implementation 'androidx.annotation:annotation:1.3.0'
    implementation 'org.lsposed.libcxx:libcxx:28.2.13676358'
}

ext {
    publishLibrary = false
    POM_NAME = "RISH"
    POM_DESCRIPTION = "RISH"
}
