
plugins {
    id 'com.android.library'
}

group 'com.reandroid.apkeditor'
version '1.4.7'

android {
    namespace 'com.reandroid.apkeditor'
    compileSdk 36
    buildToolsVersion "35.0.1"
    ndkVersion "28.2.13676358"

    defaultConfig {
        minSdk 26
        targetSdk 36
        consumerProguardFiles "consumer-rules.pro"
        externalNativeBuild {
            cmake { version "4.1.1" }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}
